name: Clojure Tests

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: git checkout
      uses: actions/checkout@v3.5.0
      with:
        ref: ${{ github.head_ref }}

    - name: Check deps
      uses: nnichols/clojure-dependency-update-action@678ae393ffe81d37e65b17c001c14aaa36731aa4
      with:
        github-token: ${{ secrets.github_token }}
        git-email: nichols1991@gmail.com
        git-username: nnichols
        skips: "pom"
