name: Clojure Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v1

    - name: Check deps
      uses: nnichols/clojure-dependency-update-action@ebf470712eab6fdaa46d5dc1f89246fef42e20eb
      with:
        github-token: ${{ secrets.github_token }}
        git-email: nichols1991@gmail.com
        git-username: nnichols
        skips: "pom"
        batch: "true"
