name: Clojure Tests

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v2.3.4

    - name: Check deps
      uses: nnichols/clojure-dependency-update-action@v4
      with:
        github-token: ${{ secrets.github_token }}
        git-email: nichols1991@gmail.com
        git-username: nnichols
        skips: "pom"
